export const searchChanged = 'search_changed'
export const showDone = 'show_done'
export const createChanged = 'create_changed'
export const createSubmited = 'create_submitted'
export const doneToggled = 'done_toggled'
export const  deleteTodo = 'delete_todo'