export const SEARCH_CHANGED = 'search_changed'
export const SHOW_DONE = 'show_done'
export const CREATE_CHANGED = 'create_changed'
export const CREATE_SUBMITTED = 'create_submitted'
export const DONE_TOGGLED = 'done_toggled'
export const  DELETE_TODO = 'delete_todo'